name: @NAME@
description: Naturally drop blocks with Silk Touch enchantment
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
permissions:
    silkpoke.basic:
        description: Can use Silk Touch enchantment to drop additional basic blocks
        default: true
        children:
            silkpoke.material.ICE: true
            silkpoke.material.WEB: true
            silkpoke.material.SNOW: true
            silkpoke.material.SOIL: true
            silkpoke.material.THIN_GLASS: true
    silkpoke.nether.ice:
        description: Can place ice in the nether
        default: false
    silkpoke.nether.water:
        description: Can create water in the nether by breaking ice
        default: false