name: @NAME@
description: Naturally drop blocks with Silk Touch enchantment
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'silkpoke:reload':
        description: Reload SilkPoke plugin
        permission: silkpoke.reload
        usage: /<command>