name: SilkPoke
version: @VERSION@
description: Naturally drop blocks with Silk Touch enchantment
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/SilkPoke
main: edgruberman.bukkit.silkpoke.Main
commands:
    'silkpoke:reload':
        description: Reload SilkPoke plugin
        permission: silkpoke.reload
        usage: /<command>